export const ADD_TODO_ACTION = "ADD_TODO_ACTION";
export const REMOVE_TODO_ACTION = "REMOVE_TODO_ACTION";
export const NEWS_ORDER_TODO_LIST = "NEWS_ORDER_TODO_LIST"
export const MOVE_TODO_LIST = 'MOVE_TODO_LIST';
export const ASSIGN_TODO = 'ASSIGN_TODO'